#! /bin/bash

set -e

if [ -f "../local" ] ; then
    source "../local"
fi

NOCACHE=

# parse arguments

while [[ $# -ge 1 ]]
do
    key="$1"

    case $key in
        -n|--no-cache)
            NOCACHE="--no-cache"
            shift # past argument
            ;;

        *)
            # unknown option
            shift # past argument or value
            ;;
    esac
done

if [[ "${USE_BUILDER}" == "no" ]] ; then
    echo skipping edvorg-builder
    exit 0
fi

echo building edvorg-builder

docker build $NOCACHE -t edvorg-builder .
