#! /bin/bash

set -e

MOUNT_DIR=${1}
WORK_DIR=${2}
COMMAND=${3}

echo "running builder mounting '${MOUNT_DIR}' exec '${COMMAND}' in '${WORK_DIR}'"

mkdir -p ~/.m2
mkdir -p ~/.lein
mkdir -p ~/.gradle

docker run --rm -t --network edvorg --hostname edvorg-builder \
       -v ~/.m2:/home/${USER}/.m2 \
       -v ~/.lein:/home/${USER}/.lein \
       -v ~/.gradle:/home/${USER}/.gradle \
       -v ${MOUNT_DIR}:/in \
       edvorg-builder sh -c "groupadd -f -g `id -g` `id -g -n` && useradd --shell /bin/bash -u `id -u` -g `id -g` -o -c \"\" `id -u -n` && cd ${WORK_DIR} && exec gosu `id -u -n` sh -c \"${COMMAND}\""

echo builder is ready
