#! /bin/bash

echo "================================================================================================"
echo "== RUNNING =================================================================================="

DIR=`dirname ${0}`
LOCAL="${DIR}/local"
LOCAL_EXAMPLE="${DIR}/local.example"

if [ ! -f "${LOCAL}" ] ; then
    cp ${LOCAL_EXAMPLE} ${LOCAL}
fi

if [ -f "${LOCAL}" ] ; then
    source "${LOCAL}"
fi

DIRS=`ls`

for entry in ${DIRS} ; do
    if [ -d ${entry} ] ; then
        echo "------------------------------------------------------------------------------------------------"
        echo entering ${entry}
        pushd ${entry}
        if [ ! -f ./run ] ; then
            echo nothing to run
        else
            ./run "$@"
            CODE=$?
            if [ "${CODE}" != "0" ] ; then
                echo failed. exiting with ${CODE}
                exit ${CODE}
            fi
        fi
        popd
    fi
done
